apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: nephos
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"
    region: "ap-southeast-1"
    objects: |
      - objectName: "nephos-dev-app-secrets"
        objectType: "secretsmanager"
        jmesPath:
          - path: "DATABASE_URL"
            objectAlias: "DATABASE_URL"
          - path: "SECRET_KEY"
            objectAlias: "SECRET_KEY"
          - path: "ALGORITHM"
            objectAlias: "ALGORITHM"
          - path: "ACCESS_TOKEN_EXPIRE"
            objectAlias: "ACCESS_TOKEN_EXPIRE"
          - path: "REFRESH_TOKEN_EXPIRE"
            objectAlias: "REFRESH_TOKEN_EXPIRE"
          - path: "STORAGE_QUOTA_BYTES"
            objectAlias: "STORAGE_QUOTA_BYTES"
  secretObjects:
    - secretName: nephos-app-secrets
      type: Opaque
      data:
        - objectName: "DATABASE_URL"
          key: DATABASE_URL          
        - objectName: "SECRET_KEY"
          key: SECRET_KEY
        - objectName: "ALGORITHM"
          key: ALGORITHM
        - objectName: "ACCESS_TOKEN_EXPIRE"
          key: ACCESS_TOKEN_EXPIRE
        - objectName: "REFRESH_TOKEN_EXPIRE"
          key: REFRESH_TOKEN_EXPIRE
        - objectName: "STORAGE_QUOTA_BYTES"
          key: STORAGE_QUOTA_BYTES

