apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: nephos
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"
    region: "ap-southeast-1"
    objects: |
      - objectName: "nephos-dev-app-secrets"
        objectType: "secretsmanager"
        jmesPath:
          - path: "DATABASE_URL"
            objectAlias: "DATABASE_URL"
          - path: "SECRET_KEY"
            objectAlias: "SECRET_KEY"
          - path: "ALGORITHM"
            objectAlias: "ALGORITHM"
          - path: "ACCESS_TOKEN_EXPIRE"
            objectAlias: "ACCESS_TOKEN_EXPIRE"
          - path: "REFRESH_TOKEN_EXPIRE"
            objectAlias: "REFRESH_TOKEN_EXPIRE"
          - path: "STORAGE_QUOTA_BYTES"
            objectAlias: "STORAGE_QUOTA_BYTES"
          - path: "API_STR"
            objectAlias: "API_STR"
          - path: "AUTH_SERVICE_URL"
            objectAlias: "AUTH_SERVICE_URL"
          - path: "BUCKET_NAME"
            objectAlias: "BUCKET_NAME"
          - path: "BUCKET_ENDPOINT_URL"
            objectAlias: "BUCKET_ENDPOINT_URL"
  secretObjects:
    - secretName: nephos-app-secrets
      type: Opaque
      data:
        - objectName: "DATABASE_URL"
          key: DATABASE_URL          
        - objectName: "SECRET_KEY"
          key: SECRET_KEY
        - objectName: "ALGORITHM"
          key: ALGORITHM
        - objectName: "ACCESS_TOKEN_EXPIRE"
          key: ACCESS_TOKEN_EXPIRE
        - objectName: "REFRESH_TOKEN_EXPIRE"
          key: REFRESH_TOKEN_EXPIRE
        - objectName: "STORAGE_QUOTA_BYTES"
          key: STORAGE_QUOTA_BYTES
        - objectName: "API_STR"
          key: API_STR
        - objectName: "AUTH_SERVICE_URL"
          key: AUTH_SERVICE_URL
        - objectName: "BUCKET_NAME"
          key: BUCKET_NAME
        - objectName: "BUCKET_ENDPOINT_URL"
          key: BUCKET_ENDPOINT_URL

