# This configures the AWS Secrets Store CSI Driver to fetch the app-secrets
# from AWS Secrets Manager and map them into a Kubernetes Secret.

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: nephos
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "nephos-dev-app-secrets"
        objectType: "secretsmanager"
  secretObjects:
    - secretName: nephos-app-secrets
      type: Opaque
      data:
        - objectName: "nephos-dev-app-secrets"
          key: JWT_SECRET_KEY
