apiVersion: v1
kind: ConfigMap
metadata:
  name: nephos-config
  namespace: nephos
data:
  ENVIRONMENT: "dev"
  AUTH_SERVICE_URL: "http://auth-service.nephos.svc.cluster.local:8000/api/v2"
  API_STR: "/api/v2"
  BUCKET_ENDPOINT_URL: "https://s3.ap-southeast-1.amazonaws.com"
  BUCKET_NAME: "nephos-dev-storage-bucket"
  REDIS_URL: "redis://redis.nephos.svc.cluster.local:6379/0"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq.nephos.svc.cluster.local:5672/"
  CORS_ORIGINS: "http://localhost:4200, https://YOUR_CLOUDFRONT_DOMAIN.cloudfront.net"
