apiVersion: v1
kind: Service
metadata:
  name: adot-collector
  namespace: amazon-cloudwatch
spec:
  # Route traffic to the ADOT pods created by the Helm release
  selector:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/instance: adot-collector
  ports:
    - name: grpc-otlp
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: http-otlp
      port: 4318
      targetPort: 4318
      protocol: TCP
  type: ClusterIP
