apiVersion: apps/v1
kind: Deployment
metadata:
  name: anime-service
  namespace: default
  labels:
    app: anime-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anime-service
  template:
    metadata:
      labels:
        app: anime-service
    spec:
      serviceAccountName: app-service-account
      containers:
        - name: anime
          # Pull the latest image from AWS ECR repository
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-southeast-1.amazonaws.com/otakutory-anime-service:latest
          ports:
            - containerPort: 8003
          env:
            - name: PYTHONPATH
              value: "/app/anime-service"
            - name: PORT
              value: "8003"
            - name: ENVIRONMENT
              value: "production"
            - name: DEBUG
              value: "False"
            # Add other required environment variables here
            # MUST define the OpenTelemetry collector endpoint for traces and metrics
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://adot-collector-opentelemetry-collector.amazon-cloudwatch.svc.cluster.local:4317"

            # MUST define a unique service name to easily identify nodes in AWS X-Ray Service Map
            - name: OTEL_SERVICE_NAME
              value: "anime-service"
---
apiVersion: v1
kind: Service
metadata:
  name: anime-service
  namespace: default
spec:
  selector:
    app: anime-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8000
  type: ClusterIP
