apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: default
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      serviceAccountName: app-service-account
      containers:
        - name: auth
          # Pull the latest image from AWS ECR repository
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-southeast-1.amazonaws.com/otakutory-auth-service:latest
          ports:
            - containerPort: 8001
          env:
            - name: PYTHONPATH
              value: "/app/auth-service"
            - name: PORT
              value: "8001"
            - name: ENVIRONMENT
              value: "production"
            # Add other required environment variables here
            - name: DEBUG
              value: "False"
            # MUST define the OpenTelemetry collector endpoint for traces and metrics
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://adot-collector-opentelemetry-collector.amazon-cloudwatch.svc.cluster.local:4317"

            # MUST define a unique service name to easily identify nodes in AWS X-Ray Service Map
            - name: OTEL_SERVICE_NAME
              value: "auth-service"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_PYTHON_LOG_CORRELATION
              value: "true"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=auth-service"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: default
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8000
  type: ClusterIP
