apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-shared-config
  namespace: default
data:
  # The endpoint now correctly points to the newly created adot-collector service
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://adot-collector.amazon-cloudwatch.svc.cluster.local:4317"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_LOGS_EXPORTER: "otlp"
  OTEL_PYTHON_LOG_CORRELATION: "true"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  # Set sampling strategy to ratio-based to reduce X-Ray ingestion costs
  OTEL_TRACES_SAMPLER: "traceidratio"
  # Only sample 10 percent of all incoming HTTP requests
  OTEL_TRACES_SAMPLER_ARG: "0.1"
