# k8s/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-service-account
  namespace: default
  annotations:
    # Attach the AWS IAM Role to this Kubernetes Service Account
    eks.amazonaws.com/role-arn: "${ROLE_ARN}"
