"""check for drift

Revision ID: 0aaa89fd4b9d
Revises: 829a2a44052f
Create Date: 2026-08-18 06:05:54.197916

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '0aaa89fd4b9d'
down_revision: str | Sequence[str] | None = '829a2a44052f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
