"""reintroduce wallets and transactions as modules

Revision ID: 5cd8449f2927
Revises: 
Create Date: 2026-08-17 10:54:27.513386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cd8449f2927'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'full_name')
    op.add_column('reviews', sa.Column('booking_id', sa.UUID(), nullable=False))
    op.add_column('reviews', sa.Column('knowledge_rating', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('communication_rating', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('video_audio_rating', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('feedback', sa.String(length=1000), nullable=True))
    op.create_unique_constraint(None, 'reviews', ['booking_id'])
    op.create_foreign_key(None, 'reviews', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.drop_column('reviews', 'comment')
    op.alter_column('skills', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skills', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.add_column('reviews', sa.Column('comment', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='unique')
    op.drop_column('reviews', 'feedback')
    op.drop_column('reviews', 'video_audio_rating')
    op.drop_column('reviews', 'communication_rating')
    op.drop_column('reviews', 'knowledge_rating')
    op.drop_column('reviews', 'booking_id')
    op.add_column('profiles', sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
