"""add duration to bookings

Revision ID: 829a2a44052f
Revises: 5cd8449f2927
Create Date: 2026-08-17 12:16:09.127579

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '829a2a44052f'
down_revision: str | Sequence[str] | None = '5cd8449f2927'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'duration')
    # ### end Alembic commands ###
